import type { Goal } from '@bolt/shared/autonomy';
import type { PanelsApi } from './PanelsSection';
import {
  addClosureEvent,
  addClosureReview,
  approveExecutionQueueItem,
  bindTaskClosureGoal,
  bindTaskClosureRun,
  clearGoal,
  completeExecutionHandoff,
  completeExecutionQueueItem,
  createCheckpoint,
  createExecutionHandoff,
  createGoal,
  createResearchBrief,
  createTaskClosure,
  failExecutionHandoff,
  failExecutionQueueItem,
  fetchExecutionAuditDiagnostics,
  fetchExecutionAuditIntegrity,
  fetchExecutionAuditTimeline,
  fetchExecutionHandoffs,
  fetchExecutionQueue,
  fetchGoalEvidence,
  fetchLocalReleaseChecklist,
  fetchPlannerGraphs,
  fetchRecoveryPolicy,
  fetchReleaseReadiness,
  fetchRunTimeline,
  fetchTaskClosureAssessment,
  fetchTaskClosureVerificationPlan,
  fetchTaskResultSummary,
  fetchTaskTemplates,
  getTaskClosure,
  getTaskClosureByRun,
  loadCheckpoint,
  pauseGoal,
  proposeExecutionQueue,
  rejectExecutionQueueItem,
  requestExecutionHandoffPermission,
  resumeGoal,
  runAgentLoop,
  steerRun,
  updateTaskClosureAssessment,
  executeResearch,
  fetchResearchScopes,
} from './harnessClientAutonomy';
import { startWorkflowRun } from './workflowClient';

type Fetcher = (input: string, init?: RequestInit) => Promise<Response>;

export function createPanelsApi(fetcher: Fetcher, goalInfo: Goal | null): PanelsApi {
  return {
    checkpoint: {
      createCheckpoint: (url: string, p: Record<string, unknown>) => createCheckpoint(url, p, fetcher),
      loadCheckpoint: (url: string, cpId: string) => loadCheckpoint(url, cpId, fetcher),
    },
    goal: {
      createGoal: (url: string, p: Record<string, unknown>) => createGoal(url, p, fetcher),
      startRun: (url: string, g: string, ws: string) => startWorkflowRun(url, g, ws, fetcher),
      runAgentLoop: (url: string, runId: string, steps: number) => runAgentLoop(url, runId, steps, fetcher),
      pauseGoal: (url: string, id: string) => pauseGoal(url, id, fetcher),
      resumeGoal: (url: string, id: string) => resumeGoal(url, id, fetcher),
      clearGoal: (url: string, id: string) => clearGoal(url, id, fetcher),
      getGoal: (_url: string, _id: string) => Promise.resolve(goalInfo),
      fetchGoalEvidence: (url: string, id: string) => fetchGoalEvidence(url, id, fetcher),
      fetchRunTimeline: (url: string, runId: string) => fetchRunTimeline(url, runId, fetcher),
    },
    sideChat: {
      steerRun: (url: string, rId: string, content: string) => steerRun(url, rId, content, fetcher),
    },
    taskClosure: {
      fetchTaskTemplates,
      createTaskClosure,
      getTaskClosure,
      addClosureEvent,
      addClosureReview,
      bindTaskClosureRun,
      bindTaskClosureGoal,
      fetchTaskClosureVerificationPlan,
      fetchTaskClosureAssessment,
      updateTaskClosureAssessment,
    },
    executionQueue: {
      fetchExecutionQueue,
      proposeExecutionQueue,
      approveExecutionQueueItem,
      rejectExecutionQueueItem,
      completeExecutionQueueItem,
      failExecutionQueueItem,
    },
    executionHandoff: {
      fetchExecutionHandoffs,
      fetchExecutionAuditTimeline,
      fetchExecutionAuditDiagnostics,
      fetchExecutionAuditIntegrity,
      fetchReleaseReadiness,
      fetchLocalReleaseChecklist,
      fetchRecoveryPolicy,
      fetchPlannerGraphs,
      createExecutionHandoff,
      completeExecutionHandoff,
      failExecutionHandoff,
      requestExecutionHandoffPermission,
    },
    researcher: {
      createBrief: createResearchBrief,
      executeResearch,
      fetchScopes: fetchResearchScopes,
    },
  };
}
