import type { Goal } from '@bolt/shared/autonomy';
import type { PanelsApi } from './PanelsSection';
import {
  addClosureEvent,
  addClosureReview,
  approveExecutionQueueItem,
  bindTaskClosureGoal,
  bindTaskClosureRun,
  clearGoal,
  completeExecutionHandoff,
  completeExecutionQueueItem,
  createCheckpoint,
  createExecutionHandoff,
  createGoal,
  createResearchBrief,
  createTaskClosure,
  failExecutionHandoff,
  failExecutionQueueItem,
  fetchExecutionAuditDiagnostics,
  fetchExecutionAuditIntegrity,
  fetchExecutionAuditTimeline,
  fetchExecutionHandoffs,
  fetchExecutionQueue,
  fetchGoalEvidence,
  fetchLocalReleaseChecklist,
  fetchPlannerGraphs,
  fetchRecoveryPolicy,
  fetchReleaseReadiness,
  fetchRunTimeline,
  fetchTaskClosureAssessment,
  fetchTaskClosureVerificationPlan,
  fetchTaskResultSummary,
  fetchTaskTemplates,
  getTaskClosure,
  getTaskClosureByRun,
  loadCheckpoint,
  pauseGoal,
  proposeExecutionQueue,
  rejectExecutionQueueItem,
  requestExecutionHandoffPermission,
  resumeGoal,
  runAgentLoop,
  steerRun,
  updateTaskClosureAssessment,
  executeResearch,
  fetchResearchScopes,
  executeBuilderTask,
  fetchBuilderProposals,
} from './harnessClientAutonomy';
import { startWorkflowRun } from './workflowClient';
import { reviewBuilderOutput, fetchReviewVerdictLabel, autoScanSkillLearner, recordFailure, runOrchestrator, fetchOrchestratorRoles, sleepAgent, wakeAgent, fetchSleepWakeStatus, freezeGate, unfreezeGate, fetchGateStatus, verifyTools, autoFixReviewFindings, autoContinueOrchestration, fetchAutoContinueStatus, runAutonomousLoop, fetchDesktopBetaShip } from './harnessClientAutonomy';

type Fetcher = (input: string, init?: RequestInit) => Promise<Response>;

export function createPanelsApi(fetcher: Fetcher, goalInfo: Goal | null): PanelsApi {
  return {
    checkpoint: {
      createCheckpoint: (p: Record<string, unknown>) => createCheckpoint(p, fetcher),
      loadCheckpoint: (cpId: string) => loadCheckpoint(cpId, fetcher),
    },
    goal: {
      createGoal: (p: Record<string, unknown>) => createGoal(p, fetcher),
      startRun: (g: string, ws: string) => startWorkflowRun(g, ws, fetcher),
      runAgentLoop: (runId: string, steps: number) => runAgentLoop(runId, steps, fetcher),
      pauseGoal: (id: string) => pauseGoal(id, fetcher),
      resumeGoal: (id: string) => resumeGoal(id, fetcher),
      clearGoal: (id: string) => clearGoal(id, fetcher),
      getGoal: (_id: string) => Promise.resolve(goalInfo),
      fetchGoalEvidence: (id: string) => fetchGoalEvidence(id, fetcher),
      fetchRunTimeline: (runId: string) => fetchRunTimeline(runId, fetcher),
    },
    sideChat: {
      steerRun: (rId: string, content: string) => steerRun(rId, content, fetcher),
    },
    taskClosure: {
      fetchTaskTemplates: () => fetchTaskTemplates(fetcher),
      createTaskClosure: (payload) => createTaskClosure(payload, fetcher),
      getTaskClosure: (id) => getTaskClosure(id, fetcher),
      addClosureEvent: (id, payload) => addClosureEvent(id, payload, fetcher),
      addClosureReview: (id, payload) => addClosureReview(id, payload, fetcher),
      bindTaskClosureRun: (id, runId) => bindTaskClosureRun(id, runId, fetcher),
      bindTaskClosureGoal: (id, goalId) => bindTaskClosureGoal(id, goalId, fetcher),
      fetchTaskClosureVerificationPlan: (id) => fetchTaskClosureVerificationPlan(id, fetcher),
      fetchTaskClosureAssessment: (id) => fetchTaskClosureAssessment(id, fetcher),
      updateTaskClosureAssessment: (id) => updateTaskClosureAssessment(id, fetcher),
    },
    executionQueue: {
      fetchExecutionQueue: (closureId) => fetchExecutionQueue(closureId, fetcher),
      proposeExecutionQueue: (closureId) => proposeExecutionQueue(closureId, fetcher),
      approveExecutionQueueItem: (itemId) => approveExecutionQueueItem(itemId, fetcher),
      rejectExecutionQueueItem: (itemId, reason) => rejectExecutionQueueItem(itemId, reason, fetcher),
      completeExecutionQueueItem: (itemId, result) => completeExecutionQueueItem(itemId, result, fetcher),
      failExecutionQueueItem: (itemId, result) => failExecutionQueueItem(itemId, result, fetcher),
    },
    executionHandoff: {
      fetchExecutionHandoffs: (closureId) => fetchExecutionHandoffs(closureId, fetcher),
      fetchExecutionAuditTimeline: (closureId) => fetchExecutionAuditTimeline(closureId, fetcher),
      fetchExecutionAuditDiagnostics: (closureId) => fetchExecutionAuditDiagnostics(closureId, fetcher),
      fetchExecutionAuditIntegrity: () => fetchExecutionAuditIntegrity(fetcher),
      fetchReleaseReadiness: () => fetchReleaseReadiness(fetcher),
      fetchLocalReleaseChecklist: () => fetchLocalReleaseChecklist(fetcher),
      fetchRecoveryPolicy: () => fetchRecoveryPolicy(fetcher),
      fetchPlannerGraphs: () => fetchPlannerGraphs(fetcher),
      createExecutionHandoff: (itemId) => createExecutionHandoff(itemId, fetcher),
      completeExecutionHandoff: (handoffId, result) => completeExecutionHandoff(handoffId, result, fetcher),
      failExecutionHandoff: (handoffId, result) => failExecutionHandoff(handoffId, result, fetcher),
      requestExecutionHandoffPermission: (handoffId) => requestExecutionHandoffPermission(handoffId, fetcher),
    },
    researcher: {
      createBrief: createResearchBrief,
      executeResearch,
      fetchScopes: fetchResearchScopes,
    },
    builder: {
      executeTask: executeBuilderTask,
      fetchProposals: fetchBuilderProposals,
    },
    reviewer: {
      reviewOutput: reviewBuilderOutput,
      fetchVerdictLabel: fetchReviewVerdictLabel,
    },
    skilllearner: { autoScan: autoScanSkillLearner, recordFailure },
    orchestrator: { runOrchestration: runOrchestrator, fetchRoles: fetchOrchestratorRoles },
    sleepWake: {
      sleep: (payload) => sleepAgent(payload, fetcher),
      wake: (payload) => wakeAgent(payload, fetcher),
      fetchStatus: () => fetchSleepWakeStatus(fetcher),
    },
    gateFreeze: { freezeGate, unfreezeGate, fetchStatus: fetchGateStatus },
    toolVerification: { verifyTools },
    autoFix: { autoFixReviewFindings },
    autoContinue: { autoContinue: autoContinueOrchestration, fetchStatus: fetchAutoContinueStatus },
    autonomousLoop: { runLoop: runAutonomousLoop },
    desktopBetaShip: { fetchBetaShip: fetchDesktopBetaShip },
  };
}
